# Generated by Django 5.2.5 on 2026-01-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artoon2d_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorcounter',
            options={'verbose_name': 'Visitor Counter', 'verbose_name_plural': 'Visitor Counters'},
        ),
    ]
